# Generated by Django 5.2 on 2025-04-28 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_pay", models.DateTimeField(verbose_name="Дата и время оплаты")),
                ("payment_amount", models.IntegerField(verbose_name="Сумма оплаты")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("online_payment", "Перевод на счет")],
                        default="online_payment",
                        max_length=15,
                        verbose_name="Способ оплаты",
                    ),
                ),
                ("content_pay", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="education.course")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
