services:
  web:
    build: .
    command: >
        bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: >
      sh -c "celery -A config worker --loglevel=info"
    env_file:
      - .env
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: >
      sh -c "celery -A config beat --loglevel=info"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery

  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis


volumes:
  postgres_data:
  static_volume:
