# Generated by Django 5.2 on 2025-04-27 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название курса", max_length=150, verbose_name="Название курса"
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Введите описание курса", max_length=250, verbose_name="Описание"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью курса",
                        null=True,
                        upload_to="education/photo",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название урока", max_length=150, verbose_name="Название урока"
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Введите описание урока", max_length=250, verbose_name="Описание"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью урока",
                        null=True,
                        upload_to="education/photo",
                        verbose_name="Изображение",
                    ),
                ),
                ("video", models.TextField(help_text="Вставьте ссылку на видео", verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["name"],
            },
        ),
    ]
