# Generated by Django 5.2.1 on 2025-05-21 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_updatesubscriptioncourse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="content_pay",
        ),
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="education.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="education.lesson",
                verbose_name="Оплаченый урок",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="link_pay",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Ссылка на платеж"),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Сессия"),
        ),
        migrations.AlterField(
            model_name="updatesubscriptioncourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_subscriptions",
                to="education.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="updatesubscriptioncourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
